# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fatimg < Formula
  desc "Go utility for creating and managing FAT32 boot (EFI) partition disk images"
  homepage "https://github.com/jsando/fatimg"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.3/fatimg_Darwin_x86_64.tar.gz"
      sha256 "eb1b8dae12d8cd431dfac43c7de5e566e6aa046d4e9006391a4459a76a466f03"

      define_method(:install) do
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.3/fatimg_Darwin_arm64.tar.gz"
      sha256 "e41d166a2d130efa0f55a222631ce25ecb9e053ec32a2ff5911aaba53fcf845d"

      define_method(:install) do
        bin.install "fatimg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.3/fatimg_Linux_x86_64.tar.gz"
      sha256 "b63f994ba6378e9ab51d185c394dd49473382bcf7162214ae9f16268d6d30e99"
      define_method(:install) do
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.3/fatimg_Linux_arm64.tar.gz"
      sha256 "f57ffc2d987955d77af8b9c1ebf67fbd6d186f45ea5ee39484fbf6d3646d59dc"
      define_method(:install) do
        bin.install "fatimg"
      end
    end
  end

  test do
    system "#{bin}/fatimg", "--version"
  end
end
