# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fatimg < Formula
  desc "Go utility for creating and managing FAT32 boot (EFI) partition disk images"
  homepage "https://github.com/jsando/fatimg"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.2/fatimg_Darwin_x86_64.tar.gz"
      sha256 "79830cee627c97109f8984c785bac6de7c88da8461aaceeafbae31458485a2b4"

      define_method(:install) do
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.2/fatimg_Darwin_arm64.tar.gz"
      sha256 "005207591f78bd59135adc271e14514786a0e1385fb23c9e69afabb646d7ca3f"

      define_method(:install) do
        bin.install "fatimg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.2/fatimg_Linux_x86_64.tar.gz"
      sha256 "83db0ca58d24e4ea60e2a325ea6fa74c4643ffb5cb3fa2f91a76c853f3ecadc3"
      define_method(:install) do
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.2/fatimg_Linux_arm64.tar.gz"
      sha256 "e72b452224fa118307207f07deba062202a9b86f219ae62821f001ba88494bd9"
      define_method(:install) do
        bin.install "fatimg"
      end
    end
  end

  test do
    system "#{bin}/fatimg", "--version"
  end
end
