# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fatimg < Formula
  desc "Go utility for creating and managing FAT32 boot (EFI) partition disk images"
  homepage "https://github.com/jsando/fatimg"
  version "0.6.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsando/fatimg/releases/download/v0.6.0/fatimg_Darwin_x86_64.tar.gz"
      sha256 "20bb6af1ce23cc564e9aad154c40aa2a2483a04d0e50ca29ea11cbb60f7c6762"

      define_method(:install) do
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsando/fatimg/releases/download/v0.6.0/fatimg_Darwin_arm64.tar.gz"
      sha256 "6092c58a20798c9175057cb4b388d7ed25ba6415b72ac6bedef85085649b4da2"

      define_method(:install) do
        bin.install "fatimg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.6.0/fatimg_Linux_x86_64.tar.gz"
      sha256 "a8abb4cfebf572d0d7afa734521bfda1d532b92b8a77fa51a44bd502fabdd9cf"
      define_method(:install) do
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.6.0/fatimg_Linux_arm64.tar.gz"
      sha256 "56a828acae7fd9022fb0ace85fb02f4472e23d202abdbb937a75a34187c0493b"
      define_method(:install) do
        bin.install "fatimg"
      end
    end
  end

  test do
    system "#{bin}/fatimg", "--version"
  end
end
